### ISSUE TITLE
Wrong arxiv link😂

### ISSUE THREAD

**Issue by littlepure2333** [XiaoCode-er/Skeleton-Based-Action-Recognition-Papers#1]
In the GCN part, 
the first paper is linked to
[Spatio-Temporal Graph Convolution for Skeleton Based Action Recognition](https://arxiv.org/abs/1802.09834)  
But actually it should link to
[Spatial Temporal Graph Convolutional Networks for Skeleton-Based Action Recognition](https://arxiv.org/abs/1801.07455)

**Comment by Anikily** [comment]
I think so.

**Comment by XiaoCode-er** [comment]
@littlepure2333 @Anikily Thanks for you attention. I have revised this link.
